<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_group' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Tue Oct 25 08:19:46 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardPlugin.lib.model
 */
class sfGuardUserGroupQuery extends BasesfGuardUserGroupQuery {

} // sfGuardUserGroupQuery
