<?php



/**
 * Skeleton subclass for representing a row from the 'file' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Oct 24 09:36:19 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class File extends BaseFile
{
  /**
   * @return string
   */
  public function __toString()
  {
    return $this->getFilename();
  }

  public function changeStatus($newStatus, $user, $con = null)
  {
    $this
      ->setStatus($newStatus)
      ->setCommitStatusChanged($this->getLastChangeCommit())
      ->setUserStatusChanged($user)
      ->setDateStatusChanged(time())
      ->save($con)
    ;
  }

  /**
   * @static
   * @param int $userId
   * @param int $repositoryId
   * @param int $branchId
   * @param int $fileId
   * @param int $oldStatus
   * @param int $newStatus
   * @param string $message
   * @return int
   */
  public static function saveAction($userId, $repositoryId, $branchId, $fileId, $oldStatus, $newStatus, $message = 'status was changed from <strong>%s</strong> to <strong>%s</strong> on the file <strong>%s</strong> of branch <strong>%s</strong>')
  {
    if ($oldStatus === $newStatus)
    {
      return 0;
    }

    $file = FileQuery::create()->filterById($fileId)->findOne();
    if(!$file)
    {
      return false;
    }

    $statusAction = new StatusAction();
    return $statusAction
      ->setUserId($userId)
      ->setRepositoryId($repositoryId)
      ->setBranchId($branchId)
      ->setFileId($fileId)
      ->setOldStatus($oldStatus)
      ->setNewStatus($newStatus)
      ->setMessage(sprintf($message, BranchPeer::getLabelStatus($oldStatus), BranchPeer::getLabelStatus($newStatus), $file->getFilename(), $file->getBranch()->__toString()))
      ->save()
    ;
  }
} // File
