<?php



/**
 * Skeleton subclass for performing query and update operations on the 'file_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Oct 24 09:36:19 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class FileCommentQuery extends BaseFileCommentQuery {

} // FileCommentQuery
