<?php



/**
 * Skeleton subclass for representing a row from the 'repository' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Oct 24 09:51:21 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Repository extends BaseRepository {
  public function __toString()
  {
    return $this->getName();
  }

  public function getGitDir()
  {
    return sprintf('%s/%s', Configuration::get('repositories_path'), $this->getValue());
  }
} // Repository
